AttachSpec("spec");
label := "88.2.a.b";
SetVerbose("ModAbVarRec", 2);
SetVerbose("ModAbVar", 2);
SetVerbose("ModularSymbols", 2);
prec := 50;
f := LMFDBNewform(label);
res := RationalGenus2Curves(f : prec:=prec);
assert #res eq 1;
b, isog, C := Explode(res[1]);
assert b;
assert Abs(Determinant(isog)) eq 1;
print "A_sub = Jac(C)";
printf "where C = %o\n", C;
// piC := PeriodMatrix(C);
//printf "Isomorphism = %o\n", isog;
